Updated scripts

diff --git a/certify b/certify
--- a/certify
+++ b/certify
@@ -36,9 +36,17 @@ export MSYS_NO_PATHCONV=1
 
 ### Helpers begin
 check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -e "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
 err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
 errx() { err "${*:2}"; exit "$1"; }
@@ -47,8 +55,8 @@ info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 long_opt() {
     local arg shift="0"
     case "$1" in
-        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 127 ;;
-        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 127; arg="$1" ;;
+        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || return 127 ;;
+        *) shift="1"; shift; [[ $# -gt 0 ]] || return 127; arg="$1" ;;
     esac
     echo "$arg"
     return $shift
@@ -302,7 +310,10 @@ usage() {
     cat <<EOF
 Usage: ${0##*/} [OPTIONS] [host1]...[hostN]
 
-Options:
+DESCRIPTION
+    Easily generate a self-signed CA issue client/server certificates.
+
+OPTIONS
     -c, --client=HOST      Create client certificate (can be used more
                            than once)
     --conf=CONFIG          Use the specified certifyme.conf (default:
@@ -327,44 +338,49 @@ wipe_pki() {
     rm -rf ca certs csr ders dh index.db* pems private
 }
 
-declare -a args clients deps
+declare -a args clients
 unset config csrfile dh help remove
 action="generate"
 color="true"
-deps+=("openssl")
 pki="${CERTIFYME_PKI:-.}"
 sslcnf="-config certifyme.openssl.cnf"
 tmpcnf="/tmp/certifyme.openssl.cnf"
 
-# Check for missing dependencies
-check_deps
-
 # Parse command line options
 while [[ $# -gt 0 ]]; do
     case "$1" in
-        "--") shift && args+=("$@") && break ;;
-        "-c"|"--client"*) clients+=("$(long_opt "$@")") || shift ;;
-        "--conf"*) config="$(long_opt "$@")" || shift ;;
-        "--csr"*) csrfile="$(long_opt "$@")" || shift ;;
+        "--") shift; args+=("$@"); break ;;
+        "-c"|"--client"*) clients+=("$(long_opt "$@")") ;;
+        "--conf"*) config="$(long_opt "$@")" ;;
+        "--csr"*) csrfile="$(long_opt "$@")" ;;
         "-d"|"--dh") dh="true" ;;
         "-h"|"--help") help="true" ;;
         "--no-color") unset color ;;
-        "-p"|"--pki"*) pki="$(long_opt "$@")" || shift ;;
-        "-r"|"--rm"*)
-            action="remove"
-            remove="$(long_opt "$@")" || shift
-            ;;
+        "-p"|"--pki"*) pki="$(long_opt "$@")" ;;
+        "-r"|"--rm"*) action="remove"; remove="$(long_opt "$@")" ;;
         "-s"|"--sample-config") action="config" ;;
         "-u"|"--undo") action="undo" ;;
         "-w"|"--wipe") action="wipe" ;;
         *) args+=("$1") ;;
     esac
+    case "$?" in
+        0) ;;
+        1) shift ;;
+        *) usage $? ;;
+    esac
     shift
 done
 [[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
 
-# Check for valid params
+# Help info
 [[ -z $help ]] || usage 0
+
+# Check for missing dependencies
+declare -a deps
+deps+=("openssl")
+check_deps
+
+# TODO Check for valid params
 
 # Get fullpath to csrfile and ensure it exists
 if [[ -n $csrfile ]]; then
